services:
  - type: web
    name: smart-scheduler-ai
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true